### ISSUE TITLE
Support for Ableton Live 9.5+

### ISSUE THREAD

**Issue by gemolnar** [lindroth/CMD_MM1_RealSession#1]
Hi,

I cannot make the script work with Ableton Live 9.6. My guess this is because the API changed in Live.
Do you have any plans to upgrade the script?

Or, are you aware of any type of guidance of how to do that? (I'm a developer too - with zero Python experience -, it could be a nice get-my-feet-wet project.)

Thanks for the script the way. ;)
-g

**Comment by lindroth** [comment]
Sorry for the long dealy. It should work for Live 10 now.
